iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
cinst git -y
cinst gittfs -y
cinst poshgit -y
cinst procexp -y
cinst xunit -y
cinst 7zip -y
cinst kdiff3 -y
cinst nuget.commandline -y
cinst bluescreenview.portable -y
cinst keepass -y
cinst foobar2000 -y
cinst python -y
cinst vim -y
#cinst virtualclonedrive -y
cinst snoop -y
cinst slack -y
cinst notepadplusplus -y
cinst palemoon -y
cinst mpv -y
cisnt snoop -y
cinst xmind -y
cinst streamlink -y
cinst universal-extractor -y
cinst pandoc -y
cinst typora -y
cinst python3 -y